// ============================================================
// Product catalogue data – Aashray
// ============================================================

export const categories = [
  {
    id: 'books',
    slug: 'books',
    name: 'Books & Stationery',
    tagline: 'Stories that stay, pages that inspire',
    color: '#8B6F47',
    accent: '#C9A96E',
    gradient: 'from-amber-50 via-orange-50 to-yellow-50/60',
    accentGrad: 'from-amber-600 via-orange-500 to-yellow-500',
    icon: 'BookOpen',
    heroImage: '📚',
    heroCaption: 'A shelf is a window — the right book, the right view.',
    features: ['Handpicked collection', 'Curated editions', 'Gift wrapping available', 'Free bookmarks'],
    transition: 'book-reveal',
  },
  {
    id: 'artwork',
    slug: 'artwork',
    name: 'Artwork & Paintings',
    tagline: 'Colour, culture, and soul on every wall',
    color: '#8B2252',
    accent: '#D4466B',
    gradient: 'from-rose-50 via-pink-50 to-fuchsia-50/60',
    accentGrad: 'from-rose-500 via-pink-500 to-fuchsia-500',
    icon: 'Palette',
    heroImage: '🎨',
    heroCaption: 'A blank wall is a story waiting to be told.',
    features: ['Museum-quality prints', 'Handmade frames', 'Artist certificates', 'Worldwide shipping'],
    transition: 'gallery-reveal',
  },
  {
    id: 'textiles',
    slug: 'textiles',
    name: 'Home Textiles',
    tagline: 'Weave comfort into every corner',
    color: '#6B4226',
    accent: '#B87333',
    gradient: 'from-orange-50 via-amber-50 to-yellow-50/60',
    accentGrad: 'from-orange-600 via-amber-500 to-yellow-500',
    icon: 'Shirt',
    heroImage: '🧵',
    heroCaption: 'Softness has a story — handloom, heritage, heart.',
    features: ['Handloom fabrics', 'Block print designs', 'Natural dyes', 'Custom sizing'],
    transition: 'curtain-reveal',
  },
  {
    id: 'decor',
    slug: 'decor',
    name: 'Lifestyle & Decor',
    tagline: 'Small details, big feelings',
    color: '#4A6741',
    accent: '#7DAF72',
    gradient: 'from-emerald-50 via-green-50 to-teal-50/60',
    accentGrad: 'from-emerald-500 via-green-500 to-teal-500',
    icon: 'Lamp',
    heroImage: '🏺',
    heroCaption: 'A room isn\'t finished until something unexpected belongs.',
    features: ['Artisan crafted', 'Sustainable materials', 'Bespoke options', 'Gift ready'],
    transition: 'shelf-reveal',
  },
  {
    id: 'electronics',
    slug: 'electronics',
    name: 'Home Electronics',
    tagline: 'Smart living, elegant technology',
    color: '#2E4057',
    accent: '#4A90D9',
    gradient: 'from-sky-50 via-blue-50 to-indigo-50/60',
    accentGrad: 'from-sky-500 via-blue-500 to-indigo-500',
    icon: 'Cpu',
    heroImage: '💡',
    heroCaption: 'Technology that doesn\'t shout — it just works beautifully.',
    features: ['Latest models', 'Free installation', '1-year warranty', 'Smart home ready'],
    transition: 'wipe-reveal',
  },
];

// ── products ────────────────────────────────────────────────────

export const products = [
  // ───── Books & Stationery ──────────────────────────────────────
  {
    id: 1,
    category: 'books',
    name: 'Atomic Habits',
    hindi: 'परमाणु आदतें',
    price: 450,
    originalPrice: 599,
    rating: 4.8,
    reviews: 3124,
    style: 'Self-Help',
    material: 'Paperback',
    badge: 'Bestseller',
    featured: true,
    color: '#F5E6D3',
    description: 'James Clear\'s transformative guide to building good habits and breaking bad ones. The #1 New York Times bestseller that has sold over 15 million copies worldwide.',
    imageSeed: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=800&h=1000&fit=crop&q=80',
    hi: 'अच्छी आदतों को बनाने और बुरी आदतों को तोड़ने की जेम्स क्लियर की परिवर्तनकारी मार्गदर्शिका।',
  },
  {
    id: 2,
    category: 'books',
    name: 'The Psychology of Money',
    hindi: 'धन का मनोविज्ञान',
    price: 399,
    originalPrice: 550,
    rating: 4.7,
    reviews: 2156,
    style: 'Finance',
    material: 'Paperback',
    badge: '#1 Bestseller',
    featured: true,
    color: '#E8F0E8',
    description: 'Morgan Housel explores the strange ways people think about money. 19 short stories about the quirky human side of finance.',
    imageSeed: 'https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1496412705862-e0088f16f791?w=800&h=1000&fit=crop&q=80',
    hi: 'मॉर्गन हाउसल लोगों के पैसे के बारे में सोचने के अजीब तरीकों की पड़ताल करते हैं।',
  },
  {
    id: 3,
    category: 'books',
    name: 'The Alchemist',
    hindi: 'रसायनी',
    price: 350,
    originalPrice: 499,
    rating: 4.6,
    reviews: 4891,
    style: 'Fiction',
    material: 'Paperback',
    badge: 'Classic',
    featured: true,
    color: '#F0E6D2',
    description: 'Paulo Coelho\'s beloved tale of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure.',
    imageSeed: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=1000&fit=crop&q=80',
    hi: 'पाउलो कोएल्हो की प्रिय कहानी — एक चरवाहा लड़के की खजाने की खोज की।',
  },
  {
    id: 4,
    category: 'books',
    name: 'Rich Dad Poor Dad',
    hindi: 'अमीर पिता गरीब पिता',
    price: 400,
    originalPrice: 500,
    rating: 4.5,
    reviews: 5230,
    style: 'Finance',
    material: 'Paperback',
    badge: 'Classic',
    featured: false,
    color: '#D9E8D9',
    description: 'Robert Kiyosaki\'s timeless lessons on money, investing, and building wealth. Over 40 million copies sold worldwide.',
    imageSeed: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&h=1000&fit=crop&q=80',
    hi: 'रॉबर्ट कियोसाकी के धन, निवेश और संपत्ति बनाने के कालातीत पाठ।',
  },
  {
    id: 5,
    category: 'books',
    name: 'Ikigai',
    hindi: 'इकिगाई',
    price: 299,
    originalPrice: 499,
    rating: 4.4,
    reviews: 2780,
    style: 'Philosophy',
    material: 'Paperback',
    badge: 'Trending',
    featured: false,
    color: '#F5E8E0',
    description: 'The Japanese secret to a long and happy life. Héctor García and Francesc Miralles explore the Okinawan concept of finding your life purpose.',
    imageSeed: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&h=1000&fit=crop&q=80',
    hi: 'एक लंबे और खुशहाल जीवन का जापानी रहस्य — अपने जीवन के उद्देश्य को खोजना।',
  },
  {
    id: 6,
    category: 'books',
    name: 'Sapiens: A Brief History of Humankind',
    hindi: 'सेपिएंस: मानवता का एक संक्षिप्त इतिहास',
    price: 499,
    originalPrice: 699,
    rating: 4.6,
    reviews: 1987,
    style: 'History',
    material: 'Paperback',
    badge: 'Editor\'s Pick',
    featured: false,
    color: '#E0E6F0',
    description: 'Yuval Noah Harari\'s groundbreaking narrative of humanity\'s creation and evolution. Explores how biology and history have defined our understanding.',
    imageSeed: 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=1000&fit=crop&q=80',
    hi: 'मानवता के सृजन और विकास की युवल नोआ हरारी की क्रांतिकारी कथा।',
  },
  {
    id: 7,
    category: 'books',
    name: 'Too Good To Be True',
    hindi: 'बहुत अच्छा सच होने के लिए',
    price: 350,
    originalPrice: 450,
    rating: 4.3,
    reviews: 876,
    style: 'Contemporary Fiction',
    material: 'Paperback',
    badge: 'New Release',
    featured: false,
    color: '#F0E0E6',
    description: 'Prajakta Koli\'s debut novel about love, dreams, and the beautiful chaos of chasing something bigger than yourself. A top Indian bestseller.',
    imageSeed: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&h=1000&fit=crop&q=80',
    hi: 'प्राजक्ता कोली का पहला उपन्यास — प्यार, सपनों और खुद से बड़ा कुछ हासिल करने की खूबसूरत अव्यवस्था।',
  },
  {
    id: 8,
    category: 'books',
    name: 'The Power of Now',
    hindi: 'अब की शक्ति',
    price: 399,
    originalPrice: 550,
    rating: 4.5,
    reviews: 1540,
    style: 'Spirituality',
    material: 'Paperback',
    badge: 'Timeless',
    featured: false,
    color: '#E8E0F0',
    description: 'Eckhart Tolle\'s guide to spiritual enlightenment through living in the present moment. A transformative read that has changed millions of lives.',
    imageSeed: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&h=1000&fit=crop&q=80',
    hi: 'एकहार्ट टोले की वर्तमान क्षण में रहकर आध्यात्मिक जागृति की मार्गदर्शिका।',
  },
  {
    id: 9,
    category: 'books',
    name: 'Deep Work',
    hindi: 'गहन कार्य',
    price: 420,
    originalPrice: 550,
    rating: 4.4,
    reviews: 1210,
    style: 'Productivity',
    material: 'Paperback',
    badge: 'Must Read',
    featured: false,
    color: '#D9E0E8',
    description: 'Cal Newport\'s rules for focused success in a distracted world. Learn to thrive in the age of constant digital interruption.',
    imageSeed: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&h=1000&fit=crop&q=80',
    hi: 'कैल न्यूपोर्ट के एकाग्रता में सफलता के नियम — बाधाओं की दुनिया में खिलना।',
  },
  {
    id: 10,
    category: 'books',
    name: 'Man\'s Search for Meaning',
    hindi: 'अर्थ की खोज',
    price: 350,
    originalPrice: 499,
    rating: 4.8,
    reviews: 2340,
    style: 'Psychology',
    material: 'Paperback',
    badge: 'Life Changing',
    featured: false,
    color: '#E0D8D0',
    description: 'Viktor Frankl\'s profound memoir of survival in Nazi concentration camps and his development of logotherapy. One of the most influential books ever written.',
    imageSeed: 'https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=800&h=1000&fit=crop&q=80',
    hi: 'विक्टर फ्रैंकल का नाजी एकाग्रता शिविरों में जीवित रहने की गहन संस्मरण।',
  },

  // ───── Artwork & Paintings ──────────────────────────────────────
  {
    id: 11,
    category: 'artwork',
    name: 'Madhubani Tree of Life',
    hindi: 'मधुबनी वृक्ष जीवन',
    price: 2200,
    originalPrice: 3500,
    rating: 4.9,
    reviews: 324,
    style: 'Traditional Indian Art',
    material: 'Handmade on handmade paper',
    badge: 'Handcrafted',
    featured: true,
    color: '#F0E0E8',
    description: 'Traditional Madhubani painting of the sacred Tree of Life motif, hand-painted by artisans from Bihar using natural dyes and cow-dung treated paper.',
    imageSeed: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&h=1000&fit=crop&q=80',
    hi: 'पवित्र वृक्ष जीवन मोटिफ की पारंपरिक मधुबनी पेंटिंग — बिहार के कारीगरों द्वारा प्राकृतिक रंगों से बनाई गई।',
  },
  {
    id: 12,
    category: 'artwork',
    name: 'Warli Village Scene',
    hindi: 'वारली गाँव दृश्य',
    price: 1800,
    originalPrice: 2800,
    rating: 4.8,
    reviews: 267,
    style: 'Tribal Art',
    material: 'Natural pigment on canvas',
    badge: 'Tribal Heritage',
    featured: true,
    color: '#E8DDD0',
    description: 'Authentic Warli tribal art depicting a lively village scene with harvest celebration. Painted using traditional rice paste on canvas.',
    imageSeed: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&h=1000&fit=crop&q=80',
    hi: 'पारंपरिक वारली आदिवासी कला — फसल उत्सव के साथ जीवंत गाँव दृश्य।',
  },
  {
    id: 13,
    category: 'artwork',
    name: 'Tanjore Ram Darbar',
    hindi: 'तंजावुर राम दरबार',
    price: 4500,
    originalPrice: 6500,
    rating: 4.9,
    reviews: 156,
    style: 'Classical South Indian',
    material: 'Gold foil on board',
    badge: 'Premium',
    featured: true,
    color: '#F5E8D0',
    description: 'Exquisite Tanjore painting of Ram Darbar featuring Lord Ram, Sita, Lakshman, and Hanuman adorned with 22-carat gold foil and semi-precious stones.',
    imageSeed: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&h=1000&fit=crop&q=80',
    hi: 'तंजावुर राम दरबार की उत्कृष्ट पेंटिंग — 22 कैरेट सोने की पन्नी और अर्ध-बहुमूल्य पत्थरों से सजी।',
  },
  {
    id: 14,
    category: 'artwork',
    name: 'Madhubani Krishna',
    hindi: 'मधुबनी कृष्ण',
    price: 1900,
    originalPrice: 3000,
    rating: 4.7,
    reviews: 198,
    style: 'Traditional Indian Art',
    material: 'Natural dyes on handmade paper',
    badge: 'Artist Signed',
    featured: false,
    color: '#E0E8F5',
    description: 'Lord Krishna depicted in the signature Madhubani style with intricate geometric patterns and peacock motifs. Hand-painted using natural pigments.',
    imageSeed: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=1000&fit=crop&q=80',
    hi: 'मधुबनी शैली में भगवान कृष्ण — जटिल ज्यामितीय पैटर्न और मोर मोटिफ के साथ।',
  },
  {
    id: 15,
    category: 'artwork',
    name: 'Warli Tree of Life',
    hindi: 'वारली वृक्ष जीवन',
    price: 1600,
    originalPrice: 2500,
    rating: 4.7,
    reviews: 210,
    style: 'Tribal Art',
    material: 'Natural pigment on cloth',
    badge: 'Bestseller',
    featured: false,
    color: '#E5DDD5',
    description: 'The iconic Warli Tree of Life motif symbolizing the connection between earth and sky, hand-painted by tribal artisans from Maharashtra.',
    imageSeed: 'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&h=1000&fit=crop&q=80',
    hi: 'प्रतिष्ठित वारली वृक्ष जीवन मोटिफ — महाराष्ट्र के आदिवासी कारीगरों द्वारा हाथ से बनाई गई।',
  },
  {
    id: 16,
    category: 'artwork',
    name: 'Tanjore Lakshmi',
    hindi: 'तंजावुर लक्ष्मी',
    price: 3800,
    originalPrice: 5500,
    rating: 4.8,
    reviews: 143,
    style: 'Classical South Indian',
    material: 'Gold foil and gems on wood',
    badge: 'Collector\'s Choice',
    featured: false,
    color: '#F5E0C8',
    description: 'Goddess Lakshmi in resplendent Tanjore style with rich gold leaf work, vibrant colors, and embedded semi-precious stones. A masterpiece of devotion.',
    imageSeed: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&h=1000&fit=crop&q=80',
    hi: 'तंजावुर शैली में देवी लक्ष्मी — समृद्ध सोने की पन्नी, जीवंत रंग और अर्ध-बहुमूल्य पत्थर।',
  },
  {
    id: 17,
    category: 'artwork',
    name: 'Warli Harvest Dance',
    hindi: 'वारली फसल नृत्य',
    price: 1500,
    originalPrice: 2200,
    rating: 4.6,
    reviews: 178,
    style: 'Tribal Art',
    material: 'Natural pigment on handmade paper',
    badge: 'Trending',
    featured: false,
    color: '#E8E0D8',
    description: 'Dynamic Warli painting showing the joyous harvest dance ritual with figures holding hands in a circle. Traditional rice-paste art from Maharashtra.',
    imageSeed: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=800&h=1000&fit=crop&q=80',
    hi: 'गतिशील वारली पेंटिंग — फसल नृत्य अनुष्ठान का आनंदमय दृश्य।',
  },
  {
    id: 18,
    category: 'artwork',
    name: 'Modern Abstract Diptych',
    hindi: 'आधुनिक अमूर्त डायप्टिक',
    price: 3200,
    originalPrice: 4800,
    rating: 4.5,
    reviews: 92,
    style: 'Contemporary Abstract',
    material: 'Acrylic on stretched canvas',
    badge: 'New Arrival',
    featured: false,
    color: '#E0E5F0',
    description: 'A stunning pair of abstract canvas paintings in complementary oceanic tones. Perfect for modern living rooms and office spaces.',
    imageSeed: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&h=1000&fit=crop&q=80',
    hi: 'समुद्री स्वरों में पूरक रंगों में एक शानदार अमूर्त कैनवास पेंटिंग जोड़ी।',
  },

  // ───── Home Textiles ────────────────────────────────────────────
  {
    id: 19,
    category: 'textiles',
    name: 'Kalamkari Tree of Life Curtain',
    hindi: 'कलमकारी वृक्ष जीवन पर्दा',
    price: 3200,
    originalPrice: 4800,
    rating: 4.8,
    reviews: 456,
    style: 'Handblock Print',
    material: '100% Pure Cotton',
    badge: 'Artisan Made',
    featured: true,
    color: '#F0E8D8',
    description: 'Authentic Machilipatnam Kalamkari curtain featuring the iconic Tree of Life motif in rich vegetable dyes. Each panel takes 3-4 days to complete.',
    imageSeed: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&h=1000&fit=crop&q=80',
    hi: 'मछिलीपट्टनम कलमकारी पर्दा — प्रतिष्ठित वृक्ष जीवन मोटिफ, समृद्ध सब्जी रंगों में।',
  },
  {
    id: 20,
    category: 'textiles',
    name: 'Jaipuri Rose Bedsheet',
    hindi: 'जयपुरी गुलाब बेडशीट',
    price: 2400,
    originalPrice: 3800,
    rating: 4.7,
    reviews: 678,
    style: 'Block Print',
    material: '100% Cotton Mulmul',
    badge: 'Bestseller',
    featured: true,
    color: '#F5E0E8',
    description: 'Handcrafted Jaipuri bedsheet with delicate rose block print pattern in soft pink and red tones on white mulmul cotton. Includes 2 pillow covers.',
    imageSeed: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&h=1000&fit=crop&q=80',
    hi: 'हस्तनिर्मित जयपुरी बेडशीट — सफेद मलमल पर नाजुक गुलाब ब्लॉक प्रिंट।',
  },
  {
    id: 21,
    category: 'textiles',
    name: 'Ajrakh Indigo Cushion Covers',
    hindi: 'अजरख नील तकिया कवर',
    price: 950,
    originalPrice: 1500,
    rating: 4.6,
    reviews: 342,
    style: 'Ajrakh Print',
    material: 'Handloom Cotton',
    badge: 'Handcrafted',
    featured: false,
    color: '#D0D8E8',
    description: 'Set of 2 traditional Ajrakh block-printed cushion covers from Kutch, Gujarat. Deep indigo blue with intricate geometric patterns using natural indigo.',
    imageSeed: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=800&h=1000&fit=crop&q=80',
    hi: '2 पारंपरिक अजरख ब्लॉक-प्रिंट तकिया कवर — कच्छ, गुजरात से गहरे नील रंग में।',
  },
  {
    id: 22,
    category: 'textiles',
    name: 'Chikankari Table Runner',
    hindi: 'चिकनकारी टेबल रनर',
    price: 1200,
    originalPrice: 1800,
    rating: 4.7,
    reviews: 189,
    style: 'Chikankari Embroidery',
    material: 'Georgette Cotton',
    badge: 'Lucknow Heritage',
    featured: false,
    color: '#F0F0F5',
    description: 'Elegant Chikankari table runner with delicate shadow work embroidery from Lucknow. Features traditional paisley and floral motifs on sheer georgette.',
    imageSeed: 'https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=800&h=1000&fit=crop&q=80',
    hi: 'लखनऊ से सुंदर चिकनकारी टेबल रनर — शैडो वर्क कढ़ाई और पारंपरिक बूटी मोटिफ।',
  },
  {
    id: 23,
    category: 'textiles',
    name: 'Kalamkari Elephant Bedsheet',
    hindi: 'कलमकारी हाथी बेडशीट',
    price: 3500,
    originalPrice: 5200,
    rating: 4.8,
    reviews: 312,
    style: 'Kalamkari',
    material: 'Handloom Cotton',
    badge: 'Heritage Craft',
    featured: false,
    color: '#E8D8C8',
    description: 'Magnificent Kalamkari bedsheet with detailed elephant procession motif in rich maroon and mustard. Hand-painted using ancient pen-work technique from Andhra Pradesh.',
    imageSeed: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=1000&fit=crop&q=80',
    hi: 'भव्य कलमकारी बेडशीट — विस्तृत हाथी जुलूस मोटिफ, समृद्ध मैरून और सरसों रंग में।',
  },
  {
    id: 24,
    category: 'textiles',
    name: 'Indigo Dabu Print Bedsheet',
    hindi: 'नील दाबू प्रिंट बेडशीट',
    price: 2800,
    originalPrice: 4200,
    rating: 4.7,
    reviews: 287,
    style: 'Dabu Print',
    material: 'Handloom Cotton',
    badge: 'Natural Dye',
    featured: false,
    color: '#C8D0E0',
    description: 'Authentic Dabu mud-resist printed bedsheet from Rajasthan in deep indigo blue. Features traditional floral vines and paisley patterns using natural indigo dye.',
    imageSeed: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&h=1000&fit=crop&q=80',
    hi: 'राजस्थान से प्रामाणिक दाबू कीच प्रतिरोधी प्रिंट बेडशीट — गहरे नील रंग में।',
  },
  {
    id: 25,
    category: 'textiles',
    name: 'Bagru Block Print Bedsheet',
    hindi: 'बगरू ब्लॉक प्रिंट बेडशीट',
    price: 2200,
    originalPrice: 3500,
    rating: 4.6,
    reviews: 234,
    style: 'Bagru Print',
    material: 'Handloom Cotton',
    badge: 'Heritage',
    featured: false,
    color: '#E8DDD0',
    description: 'Traditional Bagru printed bedsheet from Jaipur featuring earthy tones of brown, rust, and cream. Natural vegetable dyes on handloom cotton.',
    imageSeed: 'https://images.unsplash.com/photo-1595429035839-c99c298ffdde?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&h=1000&fit=crop&q=80',
    hi: 'जयपुर से पारंपरिक बगरू प्रिंट बेडशीट — मिट्टी के रंगों में प्राकृतिक सब्जी रंग।',
  },
  {
    id: 26,
    category: 'textiles',
    name: 'Phulkari Cushion Covers',
    hindi: 'फुलकारी तकिया कवर',
    price: 850,
    originalPrice: 1200,
    rating: 4.7,
    reviews: 198,
    style: 'Phulkari Embroidery',
    material: 'Handloom Cotton',
    badge: 'Punjab Heritage',
    featured: false,
    color: '#F5E8D0',
    description: 'Set of 2 vibrant Phulkari embroidered cushion covers from Punjab. Dense darning stitch in bright geometric floral patterns on natural cotton.',
    imageSeed: 'https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=1000&fit=crop&q=80',
    hi: 'पंजाब से 2 जीवंत फुलकारी कढ़ाई तकिया कवर — चमकदार ज्यामितीय फूल पैटर्न।',
  },
  {
    id: 27,
    category: 'textiles',
    name: 'Chanderi Silk Cushion Set',
    hindi: 'चंदेरी रेशम तकिया सेट',
    price: 1500,
    originalPrice: 2200,
    rating: 4.6,
    reviews: 156,
    style: 'Chanderi Weave',
    material: 'Silk-Cotton Blend',
    badge: 'Elegant',
    featured: false,
    color: '#F0E8E0',
    description: 'Set of 2 luxurious Chanderi silk-cotton blend cushion covers with subtle gold zari border. Lightweight, translucent, and elegantly understated.',
    imageSeed: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=800&h=1000&fit=crop&q=80',
    hi: '2 भव्य चंदेरी रेशम-कपास मिश्रण तकिया कवर — सूक्ष्म सोने की जरी बॉर्डर के साथ।',
  },
  {
    id: 28,
    category: 'textiles',
    name: 'Kota Doria Sheer Curtain',
    hindi: 'कोटा डोरिया शीयर पर्दा',
    price: 1800,
    originalPrice: 2800,
    rating: 4.5,
    reviews: 167,
    style: 'Kota Doria Weave',
    material: 'Cotton-Silk Blend',
    badge: 'Airy & Light',
    featured: false,
    color: '#F8F8F5',
    description: 'Ethereal Kota Doria sheer curtains from Rajasthan with delicate square weave pattern. Light filters through beautifully creating a dreamy atmosphere.',
    imageSeed: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=1000&fit=crop&q=80',
    hi: 'राजस्थान से अलौकिक कोटा डोरिया शीयर पर्दा — नाजुक वर्गाकार बुनाई पैटर्न।',
  },

  // ───── Lifestyle & Decor ────────────────────────────────────────
  {
    id: 29,
    category: 'decor',
    name: 'Handcrafted Ceramic Vase',
    hindi: 'हस्तनिर्मित सिरेमिक फूलदान',
    price: 1800,
    originalPrice: 2500,
    rating: 4.7,
    reviews: 423,
    style: 'Artisan Pottery',
    material: 'Handmade stoneware',
    badge: 'Handcrafted',
    featured: true,
    color: '#E8E0D8',
    description: 'Elegant handcrafted ceramic flower vase with a beautiful organic form. Each piece is unique — slight variations in glaze and shape make every vase one-of-a-kind.',
    imageSeed: 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=800&h=1000&fit=crop&q=80',
    hi: 'सुंदर हस्तनिर्मित सिरेमिक फूलदान — जैविक आकार के साथ, हर piece अद्वितीय।',
  },
  {
    id: 30,
    category: 'decor',
    name: 'Donut Pendant Light',
    hindi: 'डोनट पेंडेंट लाइट',
    price: 2900,
    originalPrice: 4200,
    rating: 4.8,
    reviews: 356,
    style: 'Modern Minimalist',
    material: 'Metal and glass',
    badge: 'Trending',
    featured: true,
    color: '#F5F0E8',
    description: 'Sculptural donut-shaped pendant lamp that creates a warm, ambient glow. Adjustable cord length, perfect for dining tables and kitchen islands.',
    imageSeed: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&h=1000&fit=crop&q=80',
    hi: 'स्कल्प्चरल डोनट-आकार का पेंडेंट लैम्प — गर्म, परिवेशी चमक बनाता है।',
  },
  {
    id: 31,
    category: 'decor',
    name: 'Brass Puja Diya Set',
    hindi: 'पीतल पूजा दीया सेट',
    price: 1200,
    originalPrice: 1800,
    rating: 4.9,
    reviews: 567,
    style: 'Traditional Brass',
    material: 'Pure brass',
    badge: 'Bestseller',
    featured: false,
    color: '#E8E0D0',
    description: 'Set of 5 hand-polished brass diyas for puja room and festive decoration. Traditional bell shape with intricate engraved patterns. Tarnish-resistant finish.',
    imageSeed: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=800&h=1000&fit=crop&q=80',
    hi: 'पूजा कक्ष और त्योहार की सजावट के लिए 5 हस्त-पॉलिश पीतल दीया।',
  },
  {
    id: 32,
    category: 'decor',
    name: 'Akari Mushroom Lamp',
    hindi: 'अकारी मशरूम लैम्प',
    price: 2600,
    originalPrice: 3800,
    rating: 4.7,
    reviews: 289,
    style: 'Japanese Minimalist',
    material: 'Frosted glass and steel',
    badge: 'Iconic Design',
    featured: false,
    color: '#F5F0F0',
    description: 'Inspired by Isamu Noguchi\'s Akari sculptures — a mushroom-shaped table lamp with frosted glass shade that casts a warm, diffused glow.',
    imageSeed: 'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&h=1000&fit=crop&q=80',
    hi: 'इसामु नोगुची के अकारी मूर्तियों से प्रेरित — मशरूम-आकार की टेबल लैम्प।',
  },
  {
    id: 33,
    category: 'decor',
    name: 'Aroma Reed Diffuser',
    hindi: 'अरोमा रीड डिफ्यूज़र',
    price: 950,
    originalPrice: 1400,
    rating: 4.6,
    reviews: 678,
    style: 'Wellness',
    material: 'Glass bottle with rattan reeds',
    badge: 'Self-Care',
    featured: false,
    color: '#E8F0E8',
    description: 'Premium fragrance reed diffuser with a blend of sandalwood and jasmine. 200ml bottle lasts up to 8 weeks. Creates a calming atmosphere in any room.',
    imageSeed: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1602928321679-560bb453f190?w=800&h=1000&fit=crop&q=80',
    hi: 'चंदन और चमेली के मिश्रण के साथ प्रीमियम खुशबू रीड डिफ्यूज़र — 8 सप्ताह तक चलता है।',
  },
  {
    id: 34,
    category: 'decor',
    name: 'Handblown Glass Vase',
    hindi: 'हस्त-उत्सारित ग्लास फूलदान',
    price: 2200,
    originalPrice: 3200,
    rating: 4.7,
    reviews: 198,
    style: 'Artisan Glasswork',
    material: 'Handblown borosilicate glass',
    badge: 'One of a Kind',
    featured: false,
    color: '#E0F0F0',
    description: 'Stunning handblown glass vase with organic swirls of teal and amber. Each piece is uniquely formed by master glassblowers — no two are alike.',
    imageSeed: 'https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800&h=1000&fit=crop&q=80',
    hi: 'हस्त-उत्सारित ग्लास फूलदान — टील और अंबर के जैविक घुमाव। हर piece अद्वितीय।',
  },
  {
    id: 35,
    category: 'decor',
    name: 'Rattan Pendant Light',
    hindi: 'रतन पेंडेंट लाइट',
    price: 2400,
    originalPrice: 3500,
    rating: 4.8,
    reviews: 345,
    style: 'Bohemian',
    material: 'Natural rattan',
    badge: 'Eco Friendly',
    featured: false,
    color: '#E8E0D0',
    description: 'Handwoven natural rattan pendant light that casts beautiful shadow patterns on walls. Bohemian-inspired design that brings warmth and texture to any space.',
    imageSeed: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=800&h=1000&fit=crop&q=80',
    hi: 'हस्तबुने प्राकृतिक रतन पेंडेंट लाइट — दीवारों पर खूबसूरत छाया पैटर्न बनाती है।',
  },
  {
    id: 36,
    category: 'decor',
    name: 'Brass Ganesha Figurine',
    hindi: 'पीतल गणेश मूर्ति',
    price: 1500,
    originalPrice: 2200,
    rating: 4.9,
    reviews: 456,
    style: 'Traditional Indian',
    material: 'Solid brass',
    badge: 'Spiritual',
    featured: false,
    color: '#E8E0C8',
    description: 'Beautifully crafted brass Ganesha figurine with fine detailing. Hand-painted accents on a solid brass base. Perfect for prayer room or as a meaningful gift.',
    imageSeed: 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=800&h=1000&fit=crop&q=80',
    hi: 'सुंदर शिल्प पीतल गणेश मूर्ति — ठोस पीतल आधार पर बारीक विवरण और हस्तरंगित अक्सेंट।',
  },

  // ───── Home Electronics ──────────────────────────────────────────
  {
    id: 37,
    category: 'electronics',
    name: 'Smart LED Table Lamp',
    hindi: 'स्मार्ट LED टेबल लैम्प',
    price: 3500,
    originalPrice: 5000,
    rating: 4.6,
    reviews: 876,
    style: 'Smart Home',
    material: 'Aluminium and ABS',
    badge: 'Smart Home',
    featured: true,
    color: '#D8E8F5',
    description: 'Wi-Fi enabled smart LED lamp with 16 million color options. Works with Alexa and Google Home. Adjustable color temperature from warm to cool white.',
    imageSeed: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&h=1000&fit=crop&q=80',
    hi: 'Wi-Fi सक्षम स्मार्ट LED लैम्प — 16 मिलियन रंग विकल्प, Alexa और Google Home के साथ काम करता है।',
  },
  {
    id: 38,
    category: 'electronics',
    name: 'Sunset Projection Lamp',
    hindi: 'सनसेट प्रोजेक्शन लैम्प',
    price: 1900,
    originalPrice: 2800,
    rating: 4.7,
    reviews: 1234,
    style: 'Aesthetic',
    material: 'ABS and LED',
    badge: 'Viral Hit',
    featured: true,
    color: '#F5E0D0',
    description: 'The internet-famous sunset lamp that creates a stunning golden hour glow anywhere. Adjustable arm, 360° rotation, and warm amber light.',
    imageSeed: 'https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1519974719765-e6559eac2575?w=800&h=1000&fit=crop&q=80',
    hi: 'इंटरनेट-प्रसिद्ध सनसेट लैम्प — कहीं भी शानदार गोल्डन हावर चमक बनाती है।',
  },
  {
    id: 39,
    category: 'electronics',
    name: 'Portable Bluetooth Speaker',
    hindi: 'पोर्टेबल ब्लूटूथ स्पीकर',
    price: 2500,
    originalPrice: 3800,
    rating: 4.5,
    reviews: 2345,
    style: 'Audio',
    material: 'Fabric and rubber',
    badge: 'Top Rated',
    featured: false,
    color: '#D0D8E0',
    description: 'Compact Bluetooth 5.3 speaker with 360° surround sound and 12-hour battery life. IPX7 waterproof — perfect for showers, beaches, and outdoor adventures.',
    imageSeed: 'https://images.unsplash.com/photo-1602928321679-560bb453f190?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=800&h=1000&fit=crop&q=80',
    hi: 'कॉम्पैक्ट ब्लूटूथ 5.3 स्पीकर — 360° सराउंड साउंड और 12 घंटे बैटरी लाइफ, IPX7 वाटरप्रूफ।',
  },
  {
    id: 40,
    category: 'electronics',
    name: 'Ultrasonic Aroma Diffuser',
    hindi: 'अल्ट्रासोनिक अरोमा डिफ्यूज़र',
    price: 2200,
    originalPrice: 3200,
    rating: 4.6,
    reviews: 987,
    style: 'Wellness Tech',
    material: 'Ceramic and PP',
    badge: 'Best Seller',
    featured: false,
    color: '#E0E8F0',
    description: 'Elegant ceramic ultrasonic diffuser with color-changing LED lights and auto shut-off. Runs up to 10 hours on a single fill. Whisper-quiet operation.',
    imageSeed: 'https://images.unsplash.com/photo-1602928321679-560bb453f190?w=800&h=1000&fit=crop&q=80',
    hoverSeed: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&h=1000&fit=crop&q=80',
    hi: 'सुंदर सिरेमिक अल्ट्रासोनिक डिफ्यूज़र — रंग बदलने वाली LED लाइट और ऑटो शट-ऑफ।',
  },
];

// ── aliases & helpers ────────────────────────────────────────────

export const CATEGORIES = categories;

export const getCategory = (slugOrId) =>
  categories.find((c) => c.slug === slugOrId || c.id === slugOrId);

export const getProduct = (id) =>
  products.find((p) => String(p.id) === String(id));

export const getProductsByCategory = (slug) =>
  products.filter((p) => p.category === slug);

export const getRelated = (product, n = 4) =>
  products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, n);

// ── featured products (for home page) ───────────────────────────

export const featuredProducts = products.filter((p) => p.featured);

// ── hot deals (for Deals page) ──────────────────────────────────

export const HOT_DEALS = products.filter((p) => p.originalPrice).sort(
  (a, b) =>
    b.originalPrice / b.price - a.originalPrice / a.price,
).slice(0, 8);
